// flow-typed signature: 13561f4aa7822f37fc7dd1a86a4c1556
// flow-typed version: <<STUB>>/sanitize.css_v4.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
